apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voliboli-auth-pvc
  namespace: voliboli
spec:
  storageClassName: manual
  accessModes: 
  - ReadWriteOnce
  resources: 
    requests:
      storage: 1Gi
