apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voliboli-cronjob-pvc
  namespace: voliboli
spec:
  storageClassName: manual
  accessModes: 
  - ReadWriteMany
  resources: 
    requests:
      storage: 5Gi
