apiVersion: v1
kind: PersistentVolume
metadata:
  name: voliboli-pv-auth-volume
  namespace: voliboli
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/voliboli/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: voliboli-pv-stat-volume
  namespace: voliboli
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/voliboli/stats"
